### ISSUE TITLE
Testing experimental Gmsh build to get rid of libgfortran.so dependency

### ISSUE THREAD

**Issue by geuzaine** [mrkwjc/gmsh-sdk#1]
Could you test this build and let me know if it works?

http//gmsh.info/beta/gmsh-git-Linux64-sdk.tgz

The build was generated with a custom build of gcc in order to include libgfortran.a statically in libgmsh.so.

Thanks!

Christophe

**Comment by mrkwjc** [comment]
Travis complains now about wrong libgomp.so version (on default fresh Ubuntu Trusty 14.04):

```
$ python tests.py
Traceback (most recent call last):
  File "tests.py", line 32, in <module>
    test_gmsh_import()
  File "tests.py", line 4, in test_gmsh_import
    import gmsh
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/gmsh-git-Linux64-sdk/lib/gmsh.py", line 37, in <module>
    lib = CDLL(libpath)
  File "/opt/python/2.7.14/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/gmsh-git-Linux64-sdk/lib/libgmsh.so)
The command "python tests.py" exited with 1.
```

**Comment by geuzaine** [comment]
Indeed, I was a bit cocky and I also tried to enable OpenMP in this build :-) I'll see if I can link this statically as well, or just do without (as we do now).

**Comment by geuzaine** [comment]
Here's a second try (without OpenMP - I couldn't manage to embed the lib in a clean way):

http://gmsh.info/beta/gmsh-git-Linux64-sdk.tgz

This is now built with gcc5 (to match what we do for official Windows releases).

**Comment by mrkwjc** [comment]
Now we get libstdc++ version mismatch...
 
$ python tests.py
Traceback (most recent call last):
  File "tests.py", line 32, in <module>
    test_gmsh_import()
  File "tests.py", line 4, in test_gmsh_import
    import gmsh
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/gmsh-git-Linux64-sdk/lib/gmsh.py", line 37, in <module>
    lib = CDLL(libpath)
  File "/opt/python/3.6.3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/gmsh-git-Linux64-sdk/lib/libgmsh.so)
The command "python tests.py" exited with 1.

**Comment by geuzaine** [comment]
Ok that's expected, as Ubuntu 14.04 ships with GCC 4. One more try, this time with -static-libstdc++:

http://gmsh.info/beta/gmsh-git-Linux64-sdk.tgz

**Comment by mrkwjc** [comment]
That's all right now... :)

**Comment by geuzaine** [comment]
Ok then, I'll move the official Linux builds to this config for the next release. Thanks for the testing!

**Comment by mrkwjc** [comment]
Hi!
It seems there are side effects of including libgfortran libgomp and/or libstdc++. In some configurations we will observe segfaults when importing gmsh. For example:

```
import pylab
from ctypes import CDLL
lib = CDLL('path to libgmsh.so')
```

In my linux configuration with current Anaconda with python-3.7 and gcc-8.3, the above segfaults for SDK 4.3.0, whereas it works nicely with SDK 4.2.1.

**Comment by geuzaine** [comment]
Can you run in a debugger to see where the crash happens? We've been using the binary SDK on Ubuntu 18.10 (gcc 8.2, python 2.7.15) and Ubuntu 19.04 (gcc 8.3, python 3.7.3) without issues so far.

**Comment by mrkwjc** [comment]
```
(gdb) run Tymczasowy/gmsh_debug.py 
Starting program: /home/mwojc/Anaconda/bin/python Tymczasowy/gmsh_debug.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 28249]
[New Thread 0x7fffdeaf4700 (LWP 28251)]
[New Thread 0x7fffde2f3700 (LWP 28252)]
[New Thread 0x7fffdbaf2700 (LWP 28253)]
[New Thread 0x7fffd72f1700 (LWP 28254)]
[New Thread 0x7fffd4af0700 (LWP 28255)]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffe309bf64 in std::ctype<wchar_t>::do_is(wchar_t const*, wchar_t const*, unsigned short*) const ()
   from /home/mwojc/.local/lib/python3.7/site-packages/gmsh-4.3.0-Linux64-sdk/lib/libgmsh.so
```

The gmsh_debug.py contains: 'import pylab; import gmsh':

**Comment by geuzaine** [comment]
Does it crash without `import pylab`?

**Comment by mrkwjc** [comment]
No. SDK works normally without pylab import.

**Comment by mrkwjc** [comment]
And the pylab alone works as well... However another test leads to libpng and libc. If i run the following:
```
import gmsh
import pylab
pylab.plot([0,1])
```
then the debugger gives:

```
(gdb) run Tymczasowy/gmsh_debug.py 
Starting program: /home/mwojc/Anaconda/bin/python Tymczasowy/gmsh_debug.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[Detaching after fork from child process 32130]
[New Thread 0x7fffeece2700 (LWP 32132)]
[New Thread 0x7fffee4e1700 (LWP 32133)]
[New Thread 0x7fffe9ce0700 (LWP 32134)]
[New Thread 0x7fffe94df700 (LWP 32135)]
[New Thread 0x7fffe6cde700 (LWP 32136)]
[New Thread 0x7fffd1e50700 (LWP 32138)]
libpng warning: Image width exceeds user limit in IHDR
libpng warning: Image height exceeds user limit in IHDR
libpng error: Invalid IHDR data

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007ffff7e31141 in free () from /usr/lib/libc.so.6
```

**Comment by geuzaine** [comment]
Maybe pylab and gmsh both embed their own version of libpng and/or libstdc++, which could(?) lead to conflicts?

In an ideal world we shouldn't embed any of these standard libraries... But in practice on Linux it's become really tricky to distribute a binary package without using each OS's native package distribution channel(s). In the near future both Fedora and Debian/Ubuntu will have more recent versions of Gmsh available, which will ship the dynamic lib and the C++, C and Python API. This will probably help...

**Comment by geuzaine** [comment]
The latest binary Linux SDK builds on Jupyter crashed. So we played a bit with my PhD student @MartinGrignard and it seems that the `-static-libstdc++` flag we used to embed the standard C++ lib in the .so might have been the culprit.

Could you test the latest dev SDK Linux snapshot and see if they fix the pylab issue as well?

Also, would it make sense to merge your pip packaging effort directly in the Gmsh tree, so that we could trigger an upload to the pip servers automatically for each stable release through our Gitlab CI/CD? What would that entail? I guess I would need to store some key to be able to upload to the pip registry? (Sorry for the basic questions... I'm a total beginner with pip :-))

**Comment by mrkwjc** [comment]
Unfortunately release 4.4.1 does not resolve the pylab problem, segfaults are still there. There's also new dependency for 4.4.x which was not before, i.e. 'libglu', see #3.

Testing and deploying gmsh-sdk to pypi is done via Travis service available at github. It means that i do not touch directly testing (on Ubuntu) or uploading to pypi. I do not know if your Gitlab has this possibility? If not i think there's plenty of examples around how to test and upload python code to pypi without Travis, but currently i cannot help with that... For sure you will need an account and secure string at pypi.

Obviously, you are completely free to merge 'gmsh-sdk' to the gmsh tree, if you like and i think this would make sense... Hovewer, another ways maybe easier at the moment are:
1. You can fork gmsh-sdk at github and freely edit code and make tags, but then you will need to modify .travis.yml file according to your account settings at github and pypi.
2. I can grant you a write access to my 'gmsh-sdk'.

Regards,
Marek

**Comment by geuzaine** [comment]
> Unfortunately release 4.4.1 does not resolve the pylab problem, segfaults are still there. 

Indeed, the change was made after 4.4.1 was released: can you try with the "development snapshot"?

> There's also new dependency for 4.4.x which was not before, i.e. 'libglu', see #3.

Gmsh has always depended on the OpenGL utilities (libglu) - so it's weird that the dependency did not show up before...

> 
> Testing and deploying gmsh-sdk to pypi is done via Travis service available at github. It means that i do not touch directly testing (on Ubuntu) or uploading to pypi. I do not know if your Gitlab has this possibility? If not i think there's plenty of examples around how to test and upload python code to pypi without Travis, but currently i cannot help with that... For sure you will need an account and secure string at pypi.

Ok I'll have a look. We already use our gitlab CI/CD to build, test and deploy to our own server, so I guess it should be possible to upload to pypi.

**Comment by mrkwjc** [comment]
It seems this issue is resolved...
