### ISSUE TITLE
Can't install gmsh-sdk

### ISSUE THREAD

**Issue by PeterBan11** [mrkwjc/gmsh-sdk#11]
This comand:
        $pip install gmsh-sdk
Gives this error:
        error: subprocess-exited-with-error

  × Building wheel for gmsh-sdk (pyproject.toml) did not run successfully.
ERROR: Could not build wheels for gmsh-sdk, which is required to install pyproject.toml-based projects

**Comment by mrkwjc** [comment]
This package is depereciated, since gmsh team maintains an installer... Just do `pip install gmsh`.

**Comment by PeterBan11** [comment]
It seems that pip can't find package "gmsh":
Error: Could not find a version that satisies the requirement gmsh
Error: No matching distribution found for gmsh

**Comment by mrkwjc** [comment]
Should work. See https://pypi.org/project/gmsh/
