### ISSUE TITLE
Install 'requests' package first.

### ISSUE THREAD

**Issue by jbrezmorf** [mrkwjc/gmsh-sdk#8]
Until version 4.5.1 the installation proceeds without problems, from version 4.5.2 the installation requires the previous installation of the requests package. This is unfortunate as the dependencies should be managed automatically. In particular, this breaks some of our test pipelines and makes to the users of our package which depends on the gmsh-sdk.

Seems that the problem is caused by the commit abf7ccb.
What is the problem of using old fashioned urlopen(url).read()?

Otherwise, you have to postpone import of the requests passing a suitable function to the setup method.
See the [doc](https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-resource-extraction). You have to make a function for the download, import requests in it and pass that function to the setup function as a resource.

**Comment by mrkwjc** [comment]
On some systems and configurations urlopen hangs, as reported here: https://github.com/mrkwjc/gmsh-sdk/issues/6. No other universal solution were found except requests. But you're right, this dependency should be installed automatically, i'll look into this. Pull requests are also welcomed...

**Comment by mrkwjc** [comment]
Please try updated pypi installer 4.5.4-2. Requests should be now installed automatically (and temporarily) for setup purposes. Let me know if this works for you...

**Comment by jbrezmorf** [comment]
Works like a charm. Thanks for so swift response. 
In the 'bgem' library we try to make a more pythonic wrapper for the GMSH API.

**Comment by mrkwjc** [comment]
Nice. :) Closing then.
